### Limpeza, transformação e Análise de Dados com Pandas

**O que é e quando usar o Pandas?**

In [1]:
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
%reload_ext watermark
%watermark -a "Leonardo da Silva Neves"

Author: Leonardo da Silva Neves

In [3]:
%watermark --iversions

matplotlib: 3.10.8
numpy     : 2.3.5
pandas    : 2.3.3

### 1. Pandas e Estruturas de Dados - Séries e DataFrame

Começando criando as estruturas de dados fundamentais: Série e DataFrame.

No Pandas, um Série é uma estrutura unidimensional, parecida com uma coluna de umam tabela: contém um sequência de valores com um índice associado. Já um DataFrame é um estrutura bidimensional, semelhante a uma planilha, tabela ou matriz, formada por várias colunas (que são, internamente, Séries alinhadas pelo mesmo índice).

In [4]:
# Criando um Série (uma única coluna)
s = pd.Series([10, 20, 30, 40, 50], name = 'Valores')

In [5]:
type(s)

pandas.core.series.Series

In [6]:
print("\n---Exemplo de Séries ---\n")
print(s)
print("\n")

---Exemplo de Séries ---

0    10
1    20
2    30
3    40
4    50
Name: Valores, dtype: int64

In [7]:
# Criando um dicionário em Python
dados = {
    'Nome': ['Ana', 'Bruno', 'Fabiana', 'Ronaldo', 'Eliana', 'Matias'],
    'Idade': [28, 34, 29, 17, None, 78],
    'Cidade': ['Blumenau', 'São Paulo', 'Blumenau', 'São Paulo', 'Salvador', 'São Paulo'],
    'Salario': [None, 7500, 6500, 9300, 8100, 15400]}

In [8]:
type(dados)

dict

In [9]:
print(dados)

{'Nome': ['Ana', 'Bruno', 'Fabiana', 'Ronaldo', 'Eliana', 'Matias'], 'Idade': [28, 34, 29, 17, None, 78], 'Cidade': ['Blumenau', 'São Paulo', 'Blumenau', 'São Paulo', 'Salvador', 'São Paulo'], 'Salario': [None, 7500, 6500, 9300, 8100, 15400]}

In [10]:
# Convertendo um dicionário em um DataFrame Pandas

df = pd.DataFrame(dados)

In [11]:
print("\n--- Exemplo de DataFrame ---\n")
print(df)

--- Exemplo de DataFrame ---

      Nome  Idade     Cidade  Salario
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6500.0
3  Ronaldo   17.0  São Paulo   9300.0
4   Eliana    NaN   Salvador   8100.0
5   Matias   78.0  São Paulo  15400.0

In [12]:
type(df)

pandas.core.frame.DataFrame

### 2. Leitura e Escrita de Dados no Formato .CSV

Pandas torna muito fácil salvar seu DataFrame em um arquivo .csv e carregá-lo de volta.

In [13]:
# Escrevendo (salvando) o DataFrame em um arquivo .csv
# o index=False evita que o índice do DataFrame seja salvo como uma coluno no CSV
df.to_csv('dados_funcionarios_sem_indice.csv', index=False, encoding ='utf-8')

In [14]:
# Escrevendo (salvado) o DataFrame em outro arquivo .csv
# o index=True (valor padrão) inclui o índice no DataFrame como uma coluna no CSV
df.to_csv('dados_funcionarios_com_indice.csv', index=True, encoding = 'utf-8')

In [15]:
# Lendo dados de um arquivo .csv para um novo DataFrame
df_1 = pd.read_csv('dados_funcionarios_sem_indice.csv')

In [16]:
# Visualizando as primeiras linhas
df_1.head()

      Nome  Idade     Cidade  Salario
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6500.0
3  Ronaldo   17.0  São Paulo   9300.0
4   Eliana    NaN   Salvador   8100.0

In [17]:
# Lendo dados de um arquivo .csv para um novo DataFrame
df_2 = pd.read_csv('dados_funcionarios_com_indice.csv')

In [18]:
# Visualizar as primeiras linhas
df_2.head()

   Unnamed: 0     Nome  Idade     Cidade  Salario
0           0      Ana   28.0   Blumenau      NaN
1           1    Bruno   34.0  São Paulo   7500.0
2           2  Fabiana   29.0   Blumenau   6500.0
3           3  Ronaldo   17.0  São Paulo   9300.0
4           4   Eliana    NaN   Salvador   8100.0

In [19]:
# Deletando a coluna de índice 0
df_2 = df_2.drop(df_2.columns[0], axis=1)

In [20]:
# Visualizando as primeiras linhas
df_2.head(6)

      Nome  Idade     Cidade  Salario
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6500.0
3  Ronaldo   17.0  São Paulo   9300.0
4   Eliana    NaN   Salvador   8100.0
5   Matias   78.0  São Paulo  15400.0

### 3. Seleção e Indexação com Pandas

Existem várias maneiras de selecionar dados de um DataFrame. As mais comuns são loc (baseado em rótulo) iloc (baseado em posição/índice númerico)

In [21]:
# Visualizando as primeiras linhas
df.head()

      Nome  Idade     Cidade  Salario
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6500.0
3  Ronaldo   17.0  São Paulo   9300.0
4   Eliana    NaN   Salvador   8100.0

In [22]:
# Selecionando um única coluna (retorna uma Series)
nomes = df['Nome']
print("\n--- Selecionando a coluna 'Nome' ---\n")
print(nomes)
print("\n")

--- Selecionando a coluna 'Nome' ---

0        Ana
1      Bruno
2    Fabiana
3    Ronaldo
4     Eliana
5     Matias
Name: Nome, dtype: object

In [23]:
type(nomes)

pandas.core.series.Series

In [24]:
# Selecionando multiplas colunas (retorna um DataFrame)
info_pessoal = df[['Nome', 'Idade']]
print("\n--- Selecionando as colunas 'Nome' e 'Idade' ---\n")
print(info_pessoal)
print("\n")

--- Selecionando as colunas 'Nome' e 'Idade' ---

      Nome  Idade
0      Ana   28.0
1    Bruno   34.0
2  Fabiana   29.0
3  Ronaldo   17.0
4   Eliana    NaN
5   Matias   78.0

In [25]:
type(info_pessoal)

pandas.core.frame.DataFrame

In [26]:
# Usando .loc para selecionar pela linha (rótulo/índice 1) e coluna 'Nome')
nome = df.loc[1, 'Nome']
print(f"\n--- Selecionando com o .loc[1, 'Nome'] ---\n{nome}\n")

--- Selecionando com o .loc[1, 'Nome'] ---
Bruno

In [27]:
# Usando .iloc para selecionar pela posição da linha (linha 2) e da coluna (coluna 3)
salario_fabiana = df.iloc[2, 3]
print(f"\n--- Selecionando com .iloc[2,3] ---\n{salario_fabiana}\n")

--- Selecionando com .iloc[2,3] ---
6500.0

In [28]:
# Visualizando o DataFrame
df.head(6)

      Nome  Idade     Cidade  Salario
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6500.0
3  Ronaldo   17.0  São Paulo   9300.0
4   Eliana    NaN   Salvador   8100.0
5   Matias   78.0  São Paulo  15400.0

In [29]:
# Selecionando um intervalo de linhas
primeiras_tres_linhas = df.loc[0:2] # O final (2) é inclusivo com .loc
print("\n--- Selecionando as 3 primeiras linhas com .loc ---\n")
print(primeiras_tres_linhas)

--- Selecionando as 3 primeiras linhas com .loc ---

      Nome  Idade     Cidade  Salario
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6500.0

### 4. Filtragem de Dados com Pandas

Você pode filtrar linhas com base em condições lógicas, de forma muito intuitiva, bem como usar colunas com índice.

In [30]:
# Convertendo a colunas zero em índice
df = df.set_index(df.columns[0])

In [31]:
# Visualizando
df.head(6)

         Idade     Cidade  Salario
Nome
Ana       28.0   Blumenau      NaN
Bruno     34.0  São Paulo   7500.0
Fabiana   29.0   Blumenau   6500.0
Ronaldo   17.0  São Paulo   9300.0
Eliana     NaN   Salvador   8100.0
Matias    78.0  São Paulo  15400.0

In [33]:
# Filtrando usando label do índice (linha) e da Coluna
df.loc["Fabiana", "Salario"]

np.float64(6500.0)

In [35]:
# Aplicando um filtro de forma que retorne um DataFrame. Observe a diferença sutil na síntaxe.
df.loc[["Fabiana"], ["Salario"]]

         Salario
Nome
Fabiana   6500.0

In [36]:
df = df.reset_index()

In [37]:
df.head()

      Nome  Idade     Cidade  Salario
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6500.0
3  Ronaldo   17.0  São Paulo   9300.0
4   Eliana    NaN   Salvador   8100.0

In [39]:
# Filtrando funcionários com idade superior a 30 anos
mais_30 = df[df['Idade']>30]
print("\n--- Funcionários com mais de 30 anos ---\n")
print(mais_30)
print("\n")

--- Funcionários com mais de 30 anos ---

     Nome  Idade     Cidade  Salario
1   Bruno   34.0  São Paulo   7500.0
5  Matias   78.0  São Paulo  15400.0

In [41]:
# Filtrando funcionários de São Paulo com salário acima de 6000
sp_salario = df[(df['Cidade'] == 'São Paulo') & (df['Salario']> 6000)]
print("\n--- Funcionários de São Paulo com salário > 6000 ---\n")
print(sp_salario)

--- Funcionários de São Paulo com salário > 6000 ---

      Nome  Idade     Cidade  Salario
1    Bruno   34.0  São Paulo   7500.0
3  Ronaldo   17.0  São Paulo   9300.0
5   Matias   78.0  São Paulo  15400.0

In [42]:
# Verificando quais células tem valores núlos
df.isnull()

    Nome  Idade  Cidade  Salario
0  False  False   False     True
1  False  False   False    False
2  False  False   False    False
3  False  False   False    False
4  False   True   False    False
5  False  False   False    False

In [44]:
# Verificando se há qualquer valor nulo em cada coluna
df.isnull().any()

Nome       False
Idade       True
Cidade     False
Salario     True
dtype: bool

In [45]:
# Retorna apenas as colunas que possuem pelo menos um valor nulo
df_colunas_com_nulos = df.loc[:, df.isnull().any()]

In [46]:
df_colunas_com_nulos.head()

   Idade  Salario
0   28.0      NaN
1   34.0   7500.0
2   29.0   6500.0
3   17.0   9300.0
4    NaN   8100.0

In [50]:
# Retorna apenas linhas com valores nulos
df_linhas_com_nulos = df[df.isnull().any(axis = 1)]

In [51]:
df_linhas_com_nulos.head()

     Nome  Idade    Cidade  Salario
0     Ana   28.0  Blumenau      NaN
4  Eliana    NaN  Salvador   8100.0

In [52]:
# Podemos ainda filtrar pela coluna e então verificar se há valores nulos
linhas_com_nulos_idade = df[df["Idade"].isnull()]

In [53]:
linhas_com_nulos_idade.head()

     Nome  Idade    Cidade  Salario
4  Eliana    NaN  Salvador   8100.0

### 5. Inspeção de DataFrames do Pandas

Podemos Inspecionar e resumir o dataframe de várias formas.

In [54]:
# Mostrar o número de linhas e colunas (formato)
print(f"\n--- Formato do DataFrame (.shape) ---\n{df.shape}")

--- Formato do DataFrame (.shape) ---
(6, 4)

In [55]:
# Mostrar as 3 primeiras linhas do DataFrame
print("\n--- As 3 primeiras linhas (.head(3)) ---\n")
print(df.head(3))
print("\n")

--- As 3 primeiras linhas (.head(3)) ---

      Nome  Idade     Cidade  Salario
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6500.0

In [56]:
# Mostrar as duas últimas linhas do DataFrame
print("\n--- As duas últimas linhas (.tail(2)) ---\n")
print(df.tail(2))
print("\n")

--- As duas últimas linhas (.tail(2)) ---

     Nome  Idade     Cidade  Salario
4  Eliana    NaN   Salvador   8100.0
5  Matias   78.0  São Paulo  15400.0

In [57]:
# Fornece um resumo conciso do DataFrame (tipos de dados, valores não nulos, etc.)
# Observe a contagem de valores
print("\n--- Informações gerais (.info()) ---\n")
df.info()
print("\n")

--- Informações gerais (.info()) ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nome     6 non-null      object
 1   Idade    5 non-null      float64
 2   Cidade   6 non-null      object
 3   Salario  5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [58]:
# Gera estatística descritivas de colunas numéricas
print("--- Estatísticas descritivas (.describe()) ---")
print(df.describe())
print("\n")

--- Estatísticas descritivas (.describe()) ---
           Idade       Salario
count   5.000000      5.000000
mean   37.200000   9360.000000
std    23.636836   3525.336863
min    17.000000   6500.000000
25%    28.000000   7500.000000
50%    29.000000   8100.000000
75%    34.000000   9300.000000
max    78.000000  15400.000000

In [59]:
print("\n--- Estatística descritivas (númericas e objetos) ---\n")
print(df.describe(include = 'all')) # inclui números, objetos e categorias

--- Estatística descritivas (númericas e objetos) ---

       Nome      Idade     Cidade       Salario
count     6   5.000000          6      5.000000
unique    6        NaN          3           NaN
top     Ana        NaN  São Paulo           NaN
freq      1        NaN          3           NaN
mean    NaN  37.200000        NaN   9360.000000
std     NaN  23.636836        NaN   3525.336863
min     NaN  17.000000        NaN   6500.000000
25%     NaN  28.000000        NaN   7500.000000
50%     NaN  29.000000        NaN   8100.000000
75%     NaN  34.000000        NaN   9300.000000
max     NaN  78.000000        NaN  15400.000000

In [60]:
df.describe(include = [object]) # só colunas do tipo object

       Nome     Cidade
count     6          6
unique    6          3
top     Ana  São Paulo
freq      1          3

In [61]:
df.describe(include = [np.number]) # só colunas numéricas (comportamento padrão)

           Idade       Salario
count   5.000000      5.000000
mean   37.200000   9360.000000
std    23.636836   3525.336863
min    17.000000   6500.000000
25%    28.000000   7500.000000
50%    29.000000   8100.000000
75%    34.000000   9300.000000
max    78.000000  15400.000000